#!/bin/sh
dir=$1
dir="${dir:1}"

conffile="/var/lib/mailservermega/rclone/$dir.conf"

mkdir -p /var/lib/mailservermega/mnt/$dir

/usr/bin/rclone mount \
        --config=$conffile \
        --use-mmap \
        --vfs-cache-mode writes \
        --allow-other \
        --dir-cache-time=10s \
        --cache-info-age=10s \
	--vfs-cache-max-age=1m \
        --vfs-cache-max-size=5G \
        --vfs-read-chunk-size-limit=512M \
        --cache-tmp-upload-path=/mnt/m2/tmp/rclone/upload \
        --cache-chunk-path=/mnt/m2/tmp/rclone/chunks \
        --cache-dir=/mnt/m2/tmp/rclone/vfs \
        --cache-db-path=/mnt/m2/tmp/rclone/db \
        --cache-workers=4 \
        --cache-writes \
        --stats=0 \
        --checkers=8 \
	--mega-hard-delete \
        --uid=1000 \
        --gid=1000 \
        --skip-links $dir:/ /var/lib/mailservermega/mnt/$dir
